### ISSUE TITLE
Comments entity should include a reference to a collaborator

### ISSUE THREAD

**Issue by kino90** [intesys/ytestbook#77] opened 2024-06-20 12:26 UTC
ATM Comments type is 

```typescript
export type TCommentDynamicData = {
  username: string;
  content: string;
};

export type TComment = {
  id: string;
  caseId: TCase["id"];
  testId?: TTest["id"];
  stepId?: TStep["id"];
  createdAt: number;
  testStatusWhenCreated?: StatusEnum;
  resolved: boolean;
} & TCommentDynamicData;
```

This way we cannot easily use the `Avatars` component to show the user's Avatar (in comments list, for example).

We could change it into something like :

``` typescript
export type TCommentDynamicData = {
  collaboratorId: string;
  content: string;
};
```

**Comment by nicolabosco87** [comment] 2024-06-27 12:54
duplicate of https://github.com/intesys/ytestbook/pull/84

**Closed** 2024-06-27 15:08 UTC
